php:
  image: nginx-php:${IMAGE_TAG}
  container_name: nginx-php
  ports:
    - "8081:80"
    - "28081:9001"
  volumes:
    - /local/src:/data/src
  cap_add:
    - SYS_PTRACE
  restart: unless-stopped


